---

user: max
home: "{{ansible_env.HOME}}"

container_dir: /opt/docker

home_files:
  - ".bashrc"
  - ".bash_aliases"
  - ".bash_logout"
  - ".profile"
  - ".gitconfig"

config_dirs:
 - "alacritty/"
 - "autostart"
 - "espanso"
 - "input-remapper"
 - "albert"
 - "Code/User/keybindings.json"
 - "Code/User/settings.json"
 - "Code/User/extensions.sh"
 - "gtk-2.0"
 - "gtk-3.0"
 - "gtk-4.0"
 - "lvim"
 - "tmux"
 
 
