---

- hosts: all
  tasks:
    - import_tasks: tasks/directories.yaml   # DONE
    - import_tasks: tasks/copies.yaml        # DONE
    - import_tasks: tasks/dconf.yaml         # DONE
    - import_tasks: tasks/configure.yaml     # DONE
    - import_tasks: tasks/apps.yaml          # DONE
    - import_tasks: tasks/apps-redhat.yaml   # DONE
      when: ansible_distribution == 'Fedora'
    - import_tasks: tasks/git-repos.yaml   # DONE
    - import_tasks: tasks/final.yaml   # DONE

- hosts: all
  tags: gnome-extensions
  roles:
  - role: jaredhocutt.gnome_extensions
    when: ansible_distribution == 'Fedora'
    vars:
      gnome_extension_ids:
        - 1160 # Dash To Panel
        # - 5112 # Tailscale Status

