---

- hosts: all

  tasks:
    - import_tasks: tasks/init.yaml
    - import_tasks: tasks/directories.yaml
    # - import_tasks: tasks/applications.yaml
    # - import_tasks: tasks/configure.yaml


# - hosts: all
#   roles:
#   - role: jaredhocutt.gnome_extensions
#     vars:
#       gnome_extension_ids:
#         - 5112 # Tailscale Status
#         - 1160 # Dash To Panel
#         - 906  # Sound Input & Output Device Chooser
#         - 7    # Removable Drive Menu
#         - 1319 # GS Connect


