---

- hosts: all

  tasks:
    - import_tasks: tasks/directories.yaml   # DONE
    - import_tasks: tasks/copies.yaml        # DONE
    - import_tasks: tasks/dconf.yaml         # TODO CHECK
    - import_tasks: tasks/configure.yaml     # TODO CHECK  
    - import_tasks: tasks/apps.yaml          # TODO CHECK
    - import_tasks: tasks/apps-redhat.yaml   # TODO CHECK
    - import_tasks: tasks/apps-debian.yaml   # TODO CHECK


# - hosts: all
#   roles:
#   - role: jaredhocutt.gnome_extensions
#     vars:
#       gnome_extension_ids:
#         - 5112 # Tailscale Status
#         - 1160 # Dash To Panel
#         - 906  # Sound Input & Output Device Chooser
#         - 7    # Removable Drive Menu
#         - 1319 # GS Connect


# - hosts: all
#   roles:
#   - role: jaredhocutt.gnome_extensions
      # when: ansible_distribution == 'Fedora'
#     vars:
#       gnome_extension_ids:
#         - 5112 # Tailscale Status


