---



- name: Install common cross-distro packages
  become: true
  package:
    name:
      - gimp
      - vlc
      - tcpdump
      - stow
      - neofetch
      - vim
      - net-tools
      - gnome-tweaks
      - dconf-editor
      - cmake
      - python3-pip



- name: Install common pip packages
  become: true
  pip:
    name:
      - virtualenv




# dnf only: 
# - ffmpeg-free

# dnf find:
#       - build-essential
#       - python3-venv


# ----------------------
# apt installs
# ----------------------
# - name: Install debian apps through apt
#   become: yes
#   apt:
#     update_cache: yes
#     state: present
#     name:
#       - ffmpeg
#       - build-essential
#       - libcap-dev
#       - arping
#       - x11-utils
#       - libssl-dev
#       # - virtualbox
#       # - valgrind
#       # - gdbserver
#       # --- PlatformIO ----
#       - stlink-tools
#       - python3-venv
#       - python3-pip
#       - wireshark
#       # --- ProtonVPN ---
#       - libayatana-appindicator3-1
#       - gir1.2-ayatanaappindicator3-0.1
#       - gnome-shell-extension-appindicator
#       - nala
#   tags: apps


# ----------------------
# install deb-get
# ----------------------
# - name: Install deb-get
#   shell: "curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get"
#   tags: apps

# ----------------------
# deb-get installs
# ----------------------
# - name: Install Apps available through deb-get
#   shell: "deb-get install {{item}}"
#   with_items:
#     - "discord"
#     - "code"
#     - "codium"
#     - "docker-ce"
#     - "draw.io"
#     - "signal-desktop"
#     - "tailscale"
#     - "protonvpn"
    # - "pandoc"
    # - "brave-browser"
    # - "rpi-imager"
    # - "portmaster"
    # - "spotify-client"
    # - "obs-studio"
    # - "virtualbox-6.1"
  # tags: apps


# # --------------------------------------
# # Downloaded .deb installs
# # --------------------------------------
# - name: Install .debs
#   become: true
#   apt:
#     deb: "{{item}}"
#   with_items:
#   - "https://github.com/sezanzeb/input-remapper/releases/download/2.0.0/input-remapper-2.0.0.deb"
#     # - "https://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04/amd64/albert_0.17.6-0_amd64.deb"
#     # - "https://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04/amd64/albert_0.22.0-0+553.1_amd64.deb"
#     # - "https://github.com/espanso/espanso/releases/download/v2.1.7-beta/espanso-debian-x11-amd64.deb"
#     # - "https://github.com/sezanzeb/input-remapper/releases/download/1.5.0/input-remapper-1.5.0_all.deb"
#   tags: apps


# --------------------------------------
# FLATPAK INSTALLS
# --------------------------------------
# - name: Flatpak Installs
#   flatpak:
#     name: "{{item}}"
#   with_items:
#     # - "com.mattjakeman.ExtensionManager"
#     # - "org.gnome.Boxes"
#     # - "com.usebottles.bottles"
#     # - "org.DolphinEmu.dolphin-emu"
#     # - "org.inkscape.Inkscape"
#     # - "org.audacityteam.Audacity"
#     # - "org.kicad.KiCad"
#     # - "cc.arduino.IDE2"
#     # - "com.slack.Slack"
#   tags:
#     - apps
#     - flatpak


