---




# ----------------------
# deb-get installs
# ----------------------

- name: Install Apps available through deb-get
  shell: "deb-get install {{item}}"
  with_items:
    - "brave-browser"
    - "code"
    - "discord"
    - "docker-ce"
    - "franz"
    - "neovim"
    - "obs-studio"
    - "pandoc"
    - "protonvpn"
    - "rpi-imager"
    - "signal-desktop"
    - "spotify-client"
    - "tailscale"
    - "virtualbox-6.1" 


# --------------------------------------
# Downloaded .deb installs
# --------------------------------------
- name: Install albert
  apt:
    deb: https://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04/amd64/albert_0.17.2-0_amd64.deb
  tags: apps

- name: Install espanso
  apt:
    deb: https://github.com/federico-terzi/espanso/releases/download/v2.1.5-beta/espanso-debian-x11-amd64.deb
  tags: apps

- name: Install input-remapper
  apt:
    deb: https://github.com/sezanzeb/input-remapper/releases/download/1.4.2/input-remapper-1.4.2.deb
  tags: apps


# --------------------------------------
# FLATPAK INSTALLS
# --------------------------------------
- name: Install Inkscape (flatpak)
  flatpak:
    name: org.inkscape.Inkscape
  tags: apps

- name: Install drawio (flatpak)
  flatpak:
    name: com.jgraph.drawio.desktop
  tags: apps

- name: Install Insomnia (flatpak)
  flatpak:
    name: rest.insomnia.Insomnia
  tags: apps

- name: Install onlyoffice (flatpak)
  flatpak:
    name: org.onlyoffice.desktopeditors
  tags: apps

- name: Install Gnome Extension Manager (flatpak)
  flatpak:
    name: com.mattjakeman.ExtensionManager
  tags: apps

- name: Install Dolphin Emulator (flatpak)
  flatpak:
    name: org.DolphinEmu.dolphin-emu
  tags: apps

- name: Install Minecraft (flatpak)
  flatpak:
    name: com.mojang.Minecraft
  tags: apps

- name: Install Audacity (flatpak)
  flatpak:
    name: org.audacityteam.Audacity
  tags: apps

- name: Install Bottles (flatpak)
  flatpak:
    name: com.usebottles.bottles
  tags: apps



# --------------------------------------
# Clean Up
# --------------------------------------

- name: Install autoclean
  apt:
    autoclean: yes
  tags: apps

- name: Install autoremove
  apt:
    autoremove: yes
  tags: apps
