---

# ----------------------
# apt-get installs
# ----------------------
- name: Installing software through apt
  become: yes
  apt:
    name:
      - tcpdump
      - tmux
      - ffmpeg
      - htop
      - stow
      - neofetch
      - vim
      - whois
      - gnome-tweaks
      - gnome-sushi
      - dconf-editor
      - build-essential
      - cmake
      - libcap-dev
      - arping
      - net-tools
      - x11-utils
      - build-essential
      - libssl-dev
    state: latest
  tags: apps

# ----------------------
# install deb-get
# ----------------------
# - name: Install deb-get
#   shell: "curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get"
#   tags: apps

# ----------------------
# deb-get installs
# ----------------------
# - name: Install Apps available through deb-get
#   shell: "deb-get install {{item}}"
#   with_items:
#     # - "discord"
#     # - "insomnia"
#     # - "obs-studio"
#     # - "portmaster"
#     # - "virtualbox-6.1"
#     - "brave-browser"
#     - "code"
#     - "codium"
#     - "docker-ce"
#     - "draw.io"
#     - "pandoc"
#     - "rpi-imager"
#     - "signal-desktop"
#     - "tailscale"
#   tags: apps


# --------------------------------------
# Downloaded .deb installs
# --------------------------------------
# - name: Install .debs
#   apt:
#     deb: "{{item}}"
#   with_items:
#     # - "https://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04/amd64/albert_0.17.6-0_amd64.deb"
#     - "https://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04/amd64/albert_0.22.0-0+553.1_amd64.deb"

#     # - "https://github.com/espanso/espanso/releases/download/v2.1.7-beta/espanso-debian-x11-amd64.deb"
#     - "https://github.com/sezanzeb/input-remapper/releases/download/1.5.0/input-remapper-1.5.0_all.deb"
#   tags: apps


# --------------------------------------
# FLATPAK INSTALLS
# --------------------------------------
# - name: Flatpak Installs
#   flatpak:
#     name: "{{item}}"
#   with_items:
#     - "com.mattjakeman.ExtensionManager"
#     - "org.gimp.GIMP"
#     - "org.videolan.VLC"
#     # - "org.DolphinEmu.dolphin-emu"
#     # - "org.inkscape.Inkscape"
#     # - "org.audacityteam.Audacity"
#     # - "org.kicad.KiCad"
#     # - "cc.arduino.IDE2"
#     # - "com.slack.Slack"
#     # - "com.brave.Browser"
#   tags:
#     - apps
#     - flatpak

# --------------------------------------
# Clean Up
# --------------------------------------

- name: Autoclean
  become: yes
  apt:
    autoclean: yes
  tags: apps

- name: Autoremove
  become: yes
  apt:
    autoremove: yes
  tags: apps
