---

# ----------------------
# apt-get installs
# ----------------------
- name: Installing software through apt
  become: yes
  apt:
    name:
      # Apps
      - vim
      - htop
      - neofetch
      - tmux
      - gimp
      - whois
      - vlc
      - flatpak
      - ffmpeg
      # - android-sdk-platform-tools-common
      - gnome-tweaks
      - gnome-sushi
      - dconf-editor
      - curl
      - stow
      # Linux Dev
      - build-essential
      - cmake
      - libcap-dev
      - arping
      - net-tools
      - tcpdump
      # VIRTUALIZATION
      # - virt-manager
      # - virtualbox
      # - qemu-kvm
      # - libvirt-daemon-system
      # - libvirt-clients
      # - bridge-utils
      - x11-utils
      - build-essential
      - libssl-dev
      # IPHONE MEDIA
      # - ifuse
      # - tlp
      # PROTON VPN SYS TRAY
      # - gnome-shell-extension-appindicator
      # - gir1.2-appindicator3-0.1
      # LATEX
      - pandoc
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-extra-utils
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
      - libxcb1-dev
      - libxkbcommon-dev
      - libasound2-dev
      - libudev-dev
    state: latest
  tags: apps

# ----------------------
# install deb-get
# ----------------------
- name: Install deb-get
  shell: "curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get"
  tags: apps

# ----------------------
# deb-get installs
# ----------------------
- name: Install Apps available through deb-get
  shell: "deb-get install {{item}}"
  with_items:
    - "brave-browser"
    - "code"
    - "discord"
    - "docker-ce"
    - "draw.io"
    - "insomnia"
    - "neovim"
    - "obsidian"
    - "obs-studio"
    - "pandoc"
    - "protonvpn"
    - "portmaster"
    - "rpi-imager"
    - "signal-desktop"
    - "spotify-client"
    - "tailscale"
    - "virtualbox-6.1"
  tags: apps


# --------------------------------------
# Downloaded .deb installs
# --------------------------------------
- name: Install .debs
  apt:
    deb: "{{item}}"
  with_items:
    - "https://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_22.04/amd64/albert_0.17.6-0_amd64.deb"
    - "https://github.com/espanso/espanso/releases/download/v2.1.7-beta/espanso-debian-x11-amd64.deb"
    - "https://github.com/sezanzeb/input-remapper/releases/download/1.5.0/input-remapper-1.5.0_all.deb"
  tags: apps


# --------------------------------------
# FLATPAK INSTALLS
# --------------------------------------
- name: Flatpak Installs
  flatpak:
    name: "{{item}}"
  with_items:
    - "org.inkscape.Inkscape"
    - "com.mattjakeman.ExtensionManager"
    - "org.DolphinEmu.dolphin-emu"
    - "com.mojang.Minecraft"
    - "org.audacityteam.Audacity"
    - "com.usebottles.bottles"
    - "com.valvesoftware.Steam"
  tags: apps

# --------------------------------------
# Clean Up
# --------------------------------------

- name: Install autoclean
  apt:
    autoclean: yes
  tags: apps

- name: Install autoremove
  apt:
    autoremove: yes
  tags: apps
