---


- name: Install common cross-distro packages
  become: true
  package:
    name:
      - gimp
      - vlc
      - tcpdump
      - stow
      - neofetch
      - vim
      - net-tools
      - gnome-tweaks
      - dconf-editor
      - cmake
      - python3-pip


- name: Install common pip packages
  become: true
  pip:
    name:
      - virtualenv



# --------------------------
# -- Fedora only installs --
# --------------------------
- name: Install dnf packages only
  when: ansible_distribution == 'Fedora'
  become: true
  dnf:
    name:
      - stlink
      - ffmpeg-free
      - input-remapper



# --------------------------
# -- Debian only installs --
# --------------------------
- name: Install apt packages only
  when: ansible_distribution == 'Pop!_OS' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  become: true
  apt:
    name:
      - stlink-tools
      - ffmpeg

- name: Install Input Remapper .deb
  when: ansible_distribution == 'Pop!_OS' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  become: true
  apt:
    deb: "{{item}}"
  with_items:
    - "https://github.com/sezanzeb/input-remapper/releases/download/2.0.1/input-remapper-2.0.1.deb"





# - name: Install Debian only packages
#   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
#   become: true
#   apt:
#     update_cache: true
#     name:
#       - stlink-tools
#       - ffmpeg


# - name: Install Red Hat only packages
#   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
#   become: true
#   apt:
#     update_cache: true
#     name:
#       - stlink-tools
#       - ffmpeg



# dnf only: 
# - ffmpeg-free
# - stlink

# dnf find:
#       - build-essential


# ----------------------
# apt installs
# ----------------------
# - name: Install debian apps through apt
#   become: yes
#   apt:
#     update_cache: yes
#     state: present
#     name:
#       - ffmpeg
#       - build-essential
#       - libcap-dev
#       - arping
#       - x11-utils
#       - libssl-dev
#       # - virtualbox
#       # - valgrind
#       # - gdbserver
#       # --- PlatformIO ----
#       - stlink-tools
#       - wireshark
#       # --- ProtonVPN ---
#       - libayatana-appindicator3-1
#       - gir1.2-ayatanaappindicator3-0.1
#       - gnome-shell-extension-appindicator
#       - nala
#   tags: apps


# ----------------------
# install deb-get
# ----------------------
# - name: Install deb-get
#   shell: "curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get"
#   tags: apps

# ----------------------
# deb-get installs
# ----------------------
# - name: Install Apps available through deb-get
#   shell: "deb-get install {{item}}"
#   with_items:
#     - "discord"
#     - "code"
#     - "codium"
#     - "docker-ce"
#     - "draw.io"
#     - "signal-desktop"
#     - "tailscale"
#     - "protonvpn"
    # - "pandoc"
    # - "brave-browser"
    # - "rpi-imager"
    # - "portmaster"
    # - "spotify-client"
    # - "obs-studio"
    # - "virtualbox-6.1"
  # tags: apps






# --------------------------------------
# FLATPAK INSTALLS
# --------------------------------------
# - name: Flatpak Installs
#   flatpak:
#     name: "{{item}}"
#   with_items:
#     # - "com.mattjakeman.ExtensionManager"
#     # - "org.gnome.Boxes"
#     # - "com.usebottles.bottles"
#     # - "org.DolphinEmu.dolphin-emu"
#     # - "org.inkscape.Inkscape"
#     # - "org.audacityteam.Audacity"
#     # - "org.kicad.KiCad"
#     # - "cc.arduino.IDE2"
#     # - "com.slack.Slack"
#   tags:
#     - apps
#     - flatpak


