---


# --------------------------
# -- Fedora only installs --
# --------------------------

# - name: dnf - Add tailscale repo
  # tags: apps
#   when: ansible_distribution == 'Fedora'
#   become: true
#   community.general.dnf_config_manager:
#     name: tailscale
#     baseurl: https://pkgs.tailscale.com/stable/fedora/tailscale.repo
#     enabled: yes




# TODO POP-SHELL
# TODO TRY ALBERT again
# TODO COSMIC WORKSPACES







- name: Install VScode key
  tags: apps
  become: true
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc



- name: Install Repo File
  tags: apps
  become: true
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    file: vscode



- name: dnf - Install packages
  tags: apps
  become: true
  dnf:
    update_cache: true
    name:
      - stlink
      - ffmpeg-free
      - input-remapper
      - dnf5
      - gnome-shell-extension-pop-shell
      - code

# [code]
# name=Visual Studio Code
# baseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1
# gpgcheck=1
# gpgkey=https://packages.microsoft.com/keys/microsoft.asc



#     - "discord"
#     - "code"
#     - "codium"
#     - "docker-ce"
#     - "draw.io"
#     - "signal-desktop"
#     - "tailscale"
    # - "obs-studio"


