---

- name: Install common pip packages
  tags: apps
  become: true
  pip:
    name:
      - virtualenv

# - name: Install Flathub Remote
#   become: yes
#   flatpak_remote:
#     name: flathub
#     flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Flatpak Installs
  become: true
  tags: 
    - apps
    - flatpak
  flatpak:
    name: "{{item}}"
  with_items:
    - "com.spotify.Client"
    - "com.brave.Browser"
    - "org.signal.Signal"
    - "com.jgraph.drawio.desktop"
    - "org.inkscape.Inkscape"
    - "com.mattjakeman.ExtensionManager"
    - "com.prusa3d.PrusaSlicer"
    # - "com.discordapp.Discord"
    # - "org.kicad.KiCad"

