---

- name: Install common cross-distro packages
  tags: apps
  become: true
  package:
    name:
      - vlc
      - stow
      - neofetch
      - vim
      - gnome-tweaks
      - dconf-editor
      - cmake
      - net-tools


- name: Stow settings
  shell: ./scripts/configure-stow.sh
  tags: configure


- name: Install common pip packages
  tags: apps
  become: true
  pip:
    name:
      - virtualenv


# - name: Flatpak Installs
#   tags: apps
#   flatpak:
#     name: "{{item}}"
#   with_items:
    # - "com.discordapp.Discord"
    # - todo spotify
    # - "com.mattjakeman.ExtensionManager"
    # - "org.gnome.Boxes"
    # - "com.usebottles.bottles"
    # - "org.DolphinEmu.dolphin-emu"
    # - "org.inkscape.Inkscape"
    # - "org.audacityteam.Audacity"
    # - "org.kicad.KiCad"
    # - "cc.arduino.IDE2"
    # - "com.slack.Slack"
  # tags: apps







# ----------------------
# install deb-get
# ----------------------
# - name: Install deb-get
  # tags: apps
#   shell: "curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get"
#   tags: apps

# ----------------------
# deb-get installs
# ----------------------
# - name: Install Apps available through deb-get
  # tags: apps
#   shell: "deb-get install {{item}}"
#   with_items:
#     - "discord"
#     - "code"
#     - "codium"
#     - "docker-ce"
#     - "draw.io"
#     - "signal-desktop"
#     - "tailscale"
    # - "obs-studio"
    # - "spotify-client"
#     - "protonvpn"
    # - "pandoc"
    # - "brave-browser"
    # - "rpi-imager"
    # - "portmaster"
    # - "virtualbox-6.1"
  # tags: apps






# --------------------------------------
# FLATPAK INSTALLS
# --------------------------------------



