---

- name: dnf - remove some repositories
  tags: apps
  become: true
  yum_repository:
    state: absent
    name: "{{item}}"
  with_items:
    - google-chrome
    - copr:copr.fedorainfracloud.org:phracek:PyCharm

- name: dnf - install packages
  tags: apps
  become: true
  dnf:
    update_cache: true
    name: dnf-plugins-core


# --------
#  VSCODE
# --------

- name: dnf - install VSCode key
  tags: apps
  become: true
  rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc


- name: dnf - install VSCode repo file
  tags: apps
  become: true
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc


# --------
#  DOCKER
# --------

- name: dnf - install Docker key
  tags: apps
  become: true
  rpm_key:
    key: https://download.docker.com/linux/fedora/gpg

- name: dnf - install docker repo file
  tags: apps
  become: true
  yum_repository:
    name: docker
    description: Docker Engine
    baseurl: https://download.docker.com/linux/fedora/docker-ce.repo
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/fedora/gpg


- name: dnf - install packages
  tags: apps
  become: true
  dnf:
    update_cache: true
    name:
      - stlink
      - ffmpeg-free
      - input-remapper
      - dnf5
      - gnome-shell-extension-pop-shell
      - neofetch
      - vim
      - vlc
      - gnome-tweaks
      - gimp
      - code
      - tlp
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

