---

- name: Make sure .ssh directory exists
  file:
    path: "/home/max/.ssh"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: basic

- name: Copy background file
  copy:
    src: "config_files/gnome-background"
    dest: "{{ background_file_path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: basic

- name: Copy shell file
  copy:
    src: "config_files/shell.conf"
    dest: "{{ shell_file_path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  tags: basic

