---


- name: Copy background file
  copy:
    src: "config_misc/gnome-background"
    dest: "{{ background_file_path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600


- name: Copy shell file
  copy:
    src: "config_misc/shell.conf"
    dest: "{{ shell_file_path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644



