---


- name: Copy background file
  copy:
    src: "config_misc/gnome-background"
    dest: "{{ background_file_path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600


- name: Copy shell file
  copy:
    src: "config_misc/shell.conf"
    dest: "{{ shell_file_path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644

- name: Copy clone_file
  copy:
    src: "config_misc/clone_file"
    dest: "{{ clone_file_path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644



- name: Copy gnupg directory
  tags: directories
  copy:
    src: config_misc/.gnupg
    dest: "{{ home }}"



