---

- name: Create bin directory
  file:
    path: "{{home}}/bin"
    state: directory
    mode: '0755'

- name: Create Code User directory
  file:
    path: "{{home}}/.config/Code/User/"
    state: directory
    mode: '0755'

- name: Create Codium User directory
  file:
    path: "{{home}}/.config/VSCodium/User/"
    state: directory
    mode: '0755'


- name: Copy gnupg directory
  copy:
    src: config_misc/.gnupg
    dest: "{{home}}"

