---

- name: Update and Upgrade
  become: yes
  apt:
    update_cache: yes
    upgrade: yes
  tags: essential

- name: Install Flathub Remote
  become: yes
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  tags: essential
