---

- name: Update and Upgrade
  apt:
    update_cache: yes
    upgrade: yes
  tags: essential

- name: Installing Essential Packages
  apt:
    name:
      # BASICS
      - vim
      - htop
      - neofetch
      - tmux
      - gimp
      - whois
      - flatpak
      - pandoc
      - android-sdk-platform-tools-common
      # GNOME
      - gnome-tweaks
      - dconf-editor
      - gnome-tweaks
      # VIRTUALIZATION
      - virt-manager
      - virtualbox
      - qemu-kvm
      # LINUX UTILS
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - x11-utils
      - build-essential
      - libssl-dev
      # IPHONE PHOTOS MOUNT
      - ifuse
      # PROTON VPN SYS TRAY
      - gnome-shell-extension-appindicator
      - gir1.2-appindicator3-0.1
      # BETAFLIGHT
      # - libatomic1,

    state: latest
  tags: essential
  
- name: Install Flathub Remote
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  tags: essential
