---


- name: Update default apps
  shell: ./scripts/configure-default-apps.sh
  tags: configure

- name: Install Codium/Code extensions
  shell: ./scripts/configure-code-extensions.sh
  tags: configure

