---

- name: Languages - check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes
  tags:
    - languages
    - rust

- name: Languages - download rustup
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - languages
    - rust

- name: Languages - install rustup
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - languages
    - rust
