[window]
decorations = "none"
padding.x = 8
padding.y = 4
# opacity = 0.90

[font]
size = 12.0

[font.normal]
family = "CodeNewRoman Nerd Font"
style = "Regular"

[font.bold]
family = "CodeNewRoman Nerd Font"
style = "Bold"


[cursor]
style.shape = "Beam"
thickness = 0.15

[terminal]
shell.program = "/home/max/.cargo/bin/nu"

[colors]
primary.background = "#000000"
primary.foreground = "#f8f8f8"

[env]
TERM = "xterm-256color"

#
#
# Ayu Dark theme
#
#

# Default colors
# [colors.primary]
# background = '#0A0E14'
# foreground = '#B3B1AD'

# Normal colors
[colors.normal]
black = '#01060E'
red = '#EA6C73'
green = '#91B362'
yellow = '#F9AF4F'
blue = '#53BDFA'
magenta = '#FAE994'
cyan = '#90E1C6'
white = '#C7C7C7'

# Bright colors
[colors.bright]
black = '#686868'
red = '#F07178'
green = '#C2D94C'
yellow = '#FFB454'
blue = '#59C2FF'
magenta = '#FFEE99'
cyan = '#95E6CB'
white = '#FFFFFF'
